application: angular2-seed
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: target/assets
  expiration: 1d

- url: /(.*\.(js|css|map))$
  static_files: target/\1
  upload: target/(.*\.(js|map))$
  expiration: 364d

- url: /.*
  static_files: target/index.html
  upload: target/index.html
  expiration: 0s

skip_files:
- ^(?!target).*$